version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: devops-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URL=mongodb://database:27017/devops_db
      - APP_NAME=Backend_DevOps
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    container_name: devops-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: mongo:latest
    container_name: devops-database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
